node:
  build: .
  command: 'npm run wait-watch'
  environment:
    APP_PORT: 17461
    APP_ENDPOINT: https://membres.openfab.be
    IS_EMAIL_ACTIVATED: 'false'
    EMAIL_API_KEY: ${EMAIL_API_KEY}
    EMAIL_DOMAIN: ${EMAIL_DOMAIN}
    EMAIL_FROM: 'Openfab <no-reply@mg.openfab.be>'
    EMAIL_TO: 'louis@openfab.be'
    LOG_LEVEL: debug
    NODE_ENV: development
    PG_HOST: ${PG_HOST}
    PG_PORT: ${PG_PORT}
    PG_USER: ${PG_USER}
    PG_DB: ${PG_DB}
    PG_PASSWORD: ${PG_PASSWORD}
    SECURITY_HASH_SALT: openfabiswatchingus
    SECURITY_SECRET: openfabiswatchingus
    VATLAYER_KEY: ${VATLAYER_KEY}
    # Wait for these hosts to be up before starting cmd
    WAIT_HOSTS: postgresql:5432
  ports:
    - "19461:17461"
  volumes:
    - ./config:/var/www/config
    - ./src:/var/www/src
    - ./package.json:/var/www/package.json
    - ./.sequelizerc:/var/www/.sequelizerc
    - ./db:/var/www/db
  links:
    - postgresql

postgresql:
  image: postgres:9.5
  ports:
    - "5460:5432"
