const {
  attachDeleteByIds,
  attachFindByIds,
  attachUpdateByIds
} = require('../helpers/models');

const shortid = require('shortid');

const setClassMethods = Machines => {
  Machines.findByIds = attachFindByIds(Machines);

  Machines.deleteByIds = attachDeleteByIds(Machines);

  Machines.deleteCascade = async (ids, models) => {
    return Machines.deleteByIds(ids);
  };

  Machines.updateByIds = attachUpdateByIds(Machines);
};

module.exports = (sequelize, DataTypes) => { // NOSONAR
  const Machines = sequelize.define('machines', {

    shortid: {
      type: DataTypes.TEXT,
      allowNull: false,
      unique: 'machines_short_id'
    },

    name: {
      type: DataTypes.TEXT,
      allowNull: false
    },

    description: {
      type: DataTypes.TEXT,
      allowNull: false
    },

    // It cool be nice to store a susbset of HTML generated by a webeditor
    longDescription: {
      type: DataTypes.TEXT,
      field: 'long_description'
    },

    createdAt: {
      type: DataTypes.DATE,
      field: 'created_at'
    },

    updatedAt: {
      type: DataTypes.DATE,
      field: 'updated_at'
    },

    deletedAt: {
      type: DataTypes.DATE,
      field: 'deleted_at'
    }
  }, {
    timestamps: true,
    paranoid: true,
    hooks: {
      beforeCreate (result, options) {
        result.shortId = shortid.generate();
      }
    },
    indexes: []
  });

  setClassMethods(Machines);

  return Machines;
};
